#[idris2]
#url = "/home/seagull/Projects/Idris2"
#commi = "latest:refs/heads/localmain"
#bootstrap = true

[custom.all.missing-numeric]
type = "local"
path = "."
ipkg = "missing-numeric.ipkg"
test = "test/test.ipkg"

[custom.all.missing-numeric-test]
type = "local"
path = "test"
ipkg = "test.ipkg"


