name: AnyCommit
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - $default-branch

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CC: gcc
    # container: snazzybucket/idris2:latest
    container: stefan-hoeck/idris2-pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: idris2 --version
      - run: pack install-deps
      - run: pack build missing-numeric
      - run: IDRIS2_CG=chez pack test  missing-numeric
      - run: IDRIS2_CG=refc pack test  missing-numeric
      - run: IDRIS2_CG=node pack test  missing-numeric
      - run: pack install missing-numeric

